spring:
  application:
    name: microservice-lecturer
  profiles:
    default: dev
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
server:
  port: 8081